name: express
description: Include express as dependence
types:
  - app
hooks:
  - type: edit-json
    trigger: after-render
    path: package.json
    indent: 2
    encoding: utf-8
    changes:
      - jsonpath: "$."
        update:
          value: |
            "dependencies": {
              "express": "^4.18.1"
            }

