name: express
description: Include express as dependence
types:
  - app
hooks:
  - type: edit-json
    trigger: after-render
    path: package.json
    indent: 2
    encoding: utf-8
    changes:
      - jsonpath: "$.dependencies"
        update:
          value: |
            { "express": "^4.18.1" }
  - type: edit-yaml
    trigger: after-render
    path: docker-compose.yaml
    changes:
      - yamlpath: "$.services.web"
        update:
          value: |
            ports:
              - "3000:3000"
  - type: edit
    trigger: after-render
    path: index.js
    changes:
      - insert:
          line: -1
          snippet: snippets/index.js
          when:
            not-exists: const express = require('express')
  - type: run
    trigger: after-render
    commands:
      - npm install
